git: Check if prettier exists in pre-commit hook

diff --git a/.git_hooks/pre-commit b/.git_hooks/pre-commit
--- a/.git_hooks/pre-commit
+++ b/.git_hooks/pre-commit
@@ -1,9 +1,16 @@
 #!/bin/sh
+PRETTIER=./node_modules/.bin/prettier
+
+if [ ! -f "$PRETTIER" ]; then
+  echo "prettier not found; run 'npm install' before commit to enable auto-formatting"
+  exit 1
+fi
+
 jsfiles=$(git diff --cached --name-only --diff-filter=ACM "*.js" "*.jsx" | tr '\n' ' ')
 [ -z "$jsfiles" ] && exit 0
 
 # Prettify all staged .js files
-echo "$jsfiles" | xargs ./node_modules/.bin/prettier --write
+echo "$jsfiles" | xargs $PRETTIER --write
 
 # Add back the modified/prettified files to staging
 echo "$jsfiles" | xargs git add
